on_market/apps/registration/urls.py
from django.urls import path
from . import views


app_name = 'registration'
urlpatterns = [
	path('', views.show_form),
	path('success/', views.leave_form, name = 'leave_form')
]

on_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from registration.views import check_form

def main_page_call(request):
	return render(request, 'main_page.html')

urlpatterns = [
    path('', main_page_call),
    path('registration/', include('registration.urls')),
    path('check_form/', check_form, name = 'check_form'),
    path('admin/', admin.site.urls),
]

on_market/templates/autorised_page.html
{% extends 'base.html' %}
{% load static %}


{% block links %}
	<link rel="stylesheet" href="{% static 'css/autorised_page.css' %}">
{% endblock links %}


{% block title %}
	Main menu
{% endblock title %}


{% block header %}
	<a id="username" href="#">{{ login }}</a>
{% endblock header %}


{% block main %}
	<div id="post_main_div">
		<div class="main_content category"></div>
		<div class="main_content product"></div>
		<div class="main_content news"></div>
	</div>
{% endblock main %}


{% block footer %}
	
{% endblock footer %}

on_market/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% block links %}{% endblock links %}
	<title>{% block title %}{% endblock title%}</title>
</head>
<body>
	<div id="container">
		<header>
			<a href="http://127.0.0.1:8000/" id="site_name_link"><p id="site_name">my-market.net</p></a>
			{% block header %}
			{% endblock header %}
		</header>
		<main>
			{% block main %}
			{% endblock main %}
		</main>
		<footer>
			{% block footer %}
			{% endblock footer %}
		</footer>
	</div>
</body>
</html>

on_market/templates/isnt_registrated_page.html
{% extends 'base.html' %}
{% load static %}


{% block links %}
	<link rel="stylesheet" href="{% static 'css/isnt_registrated_page.css' %}">
{% endblock links %}


{% block title %}
	Main menu
{% endblock title %}


{% block header %}
	<input type="checkbox" id="autorisation">
	<label for="autorisation">
		<div id="wall">
			<form action="{% url 'check_form' %}" method="POST" id="blank">
				{% csrf_token %}
				<div id="isnt_registrated">
					<p id="incorrect">Неверный логин или пароль!!!</p>
					<p>Если Вы еще не были зарегистрированы! Зарегистрироваться можете по этой <a href="http://127.0.0.1:8000/registration/">ссылке</a>!</p>
				</div>
				<input type="text" form="blank" placeholder="Логин" name="login">
				<input type="text" form="blank" placeholder="Пароль" name="password">
				<button type="submit">Отправить</button>
			</form>
		</div>
	</label>
	<label for="autorisation" id="sec_label"></label>
{% endblock header %}


{% block main %}
	<div id="post_main_div">
		<div class="main_content category"></div>
		<div class="main_content product"></div>
		<div class="main_content news"></div>
	</div>
{% endblock main %}


{% block footer %}
	
{% endblock footer %}

on_market/templates/main_page.html
{% extends 'base.html' %}
{% load static %}


{% block links %}
	<link rel="stylesheet" href="{% static 'css/main_page_style.css' %}">
{% endblock links %}


{% block title %}
	My-market
{% endblock title %}


{% block header %}
	<input type="checkbox" id="autorisation">
	<label for="autorisation">
		<div id="wall">
			<form action="{% url 'check_form' %}" method="POST" id="blank">
				{% csrf_token %}
				<input type="text" form="blank" required placeholder="Логин" name="login">
				<input type="text" form="blank" required placeholder="Пароль" name="password">
				<button type="submit">Отправить</button>
			</form>
		</div>
	</label>
	<label for="autorisation" id="sec_label"></label>
{% endblock header %}


{% block main %}
	<div id="post_main_div">
		<div class="main_content category"></div>
		<div class="main_content product"></div>
		<div class="main_content news"></div>
	</div>
{% endblock main %}


{% block footer %}
	
{% endblock footer %}

on_market/templates/registration_page.html
{% extends 'base.html' %}
{% load static %}


{% block links %}
	<link rel="stylesheet" href="{% static 'css/registration_page.css' %}">
{% endblock links %}


{% block title %}
	Registration
{% endblock title %}


{% block header %}
	
{% endblock header %}


{% block main %}
	<form action="{% url 'registration:leave_form' %}" method="POST" id="blank">
		{% csrf_token %}
		<input type="text" form="blank" required placeholder="Логин" name="login">
		<input type="text" form="blank" required placeholder="Пароль" name="password">
		<input type="text" form="blank" required placeholder="E-mail" name="e_mail">
		<button type="submit">Зарегистрироваться!</button>
	</form>
{% endblock main %}


{% block footer %}
	
{% endblock footer %}